#!/bin/bash
# Cloudinary Setup Helper
# This script helps you get Cloudinary credentials

echo "═══════════════════════════════════════════════════════════════"
echo "  Cloudinary Account Setup for Spilled Palette"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Since browser automation is not available, please:"
echo ""
echo "1. Visit: https://cloudinary.com/users/register/free"
echo "2. Sign up with your email (or Google/GitHub account)"
echo "3. Once logged in, go to: Dashboard → Account Details"
echo "4. Copy these values:"
echo ""
echo "   ☁️  Cloud Name:  (e.g., 'spilledpalette')"
echo "   🔑 API Key:     (e.g., '123456789012345')"
echo "   🔒 API Secret:  (e.g., 'aBcD...')"
echo ""
echo "5. Run this command with your credentials:"
echo ""
echo "   export CLOUDINARY_CLOUD_NAME='your_cloud_name'"
echo "   export CLOUDINARY_API_KEY='your_api_key'"
echo "   export CLOUDINARY_API_SECRET='your_api_secret'"
echo ""
echo "6. Then run the upload:"
echo "   node ~/Projects/spilledpalette/scripts/upload-artworks.js"
echo ""
echo "═══════════════════════════════════════════════════════════════"
